services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: eventhub-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - NUXT_PUBLIC_SITE_URL=${NUXT_PUBLIC_SITE_URL:-http://localhost:3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_METRICS=${ENABLE_METRICS:-true}
    env_file:
      - .env.production
    restart: unless-stopped
    
    # Health checks for reliability
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Security configurations
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/cache:noexec,nosuid,size=50m
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    
    # Logging configuration with structured logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        labels: "service=eventhub,environment=production,version=${VERSION:-latest}"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    
    # Volume mounts for logs and cache
    volumes:
      - app-logs:/app/logs
      - app-cache:/app/.nuxt/cache
    
    # Network configuration
    networks:
      - eventhub-network
    
    # Labels for monitoring and management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eventhub.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.eventhub.loadbalancer.server.port=3000"
      - "traefik.http.routers.eventhub.tls=true"
      - "com.docker.compose.service=eventhub"
      - "com.docker.compose.project=eventhub-prod"
      - "com.docker.compose.version=${VERSION:-latest}"
      - "monitoring.enable=true"
      - "backup.enable=false"

networks:
  eventhub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  app-logs:
    driver: local
  app-cache:
    driver: local